import type { PdfToolDefinition } from './types'

export const pdfTools: PdfToolDefinition[] = [
  {
    id: 'merge',
    title: 'Merge PDF',
    description: 'Combine multiple PDF files into one organized document.',
    icon: '🧩',
    mode: 'pdf',
    acceptsMultiple: true,
    outputLabel: 'merged-document.pdf',
  },
  {
    id: 'split',
    title: 'Split PDF',
    description: 'Split every page of a PDF into separate files packed in a ZIP.',
    icon: '✂️',
    mode: 'pdf',
    acceptsMultiple: false,
    outputLabel: 'split-pages.zip',
  },
  {
    id: 'compress',
    title: 'Compress PDF',
    description: 'Optimize a PDF locally using object streams and clean saving.',
    icon: '🗜️',
    mode: 'pdf',
    acceptsMultiple: false,
    outputLabel: 'compressed-document.pdf',
  },
  {
    id: 'rotate',
    title: 'Rotate PDF',
    description: 'Rotate all pages or selected pages by 90, 180, or 270 degrees.',
    icon: '🔄',
    mode: 'pdf',
    acceptsMultiple: false,
    outputLabel: 'rotated-document.pdf',
  },
  {
    id: 'delete',
    title: 'Delete Pages',
    description: 'Remove selected pages and export a clean PDF.',
    icon: '🗑️',
    mode: 'pdf',
    acceptsMultiple: false,
    outputLabel: 'pages-deleted.pdf',
  },
  {
    id: 'extract',
    title: 'Extract Pages',
    description: 'Extract selected pages into a new PDF file.',
    icon: '📄',
    mode: 'pdf',
    acceptsMultiple: false,
    outputLabel: 'extracted-pages.pdf',
  },
  {
    id: 'reorder',
    title: 'Reorder Pages',
    description: 'Create a new PDF using a custom page order.',
    icon: '↕️',
    mode: 'pdf',
    acceptsMultiple: false,
    outputLabel: 'reordered-document.pdf',
  },
  {
    id: 'imageToPdf',
    title: 'Image to PDF',
    description: 'Convert JPG and PNG files into a single multi-page PDF.',
    icon: '🖼️',
    mode: 'image',
    acceptsMultiple: true,
    outputLabel: 'images-document.pdf',
  },
  {
    id: 'pdfToImage',
    title: 'PDF to Image',
    description: 'Render every PDF page as high-quality PNG images in a ZIP.',
    icon: '🌄',
    mode: 'pdf',
    acceptsMultiple: false,
    outputLabel: 'pdf-images.zip',
  },
]
