import type { PdfToolDefinition } from './types'

export const pdfTools: PdfToolDefinition[] = [
  {
    id: 'merge',
    title: 'Merge PDF',
    description: 'Combine multiple PDF files into one organized document.',
    icon: '🧩',
    mode: 'pdf',
    acceptsMultiple: true,
    outputLabel: 'merged-document.pdf',
  },
  {
    id: 'organize',
    title: 'Organize PDF',
    description: 'Visually reorder, rotate, duplicate, or insert blank pages in a PDF.',
    icon: '🧭',
    mode: 'pdf',
    acceptsMultiple: false,
    outputLabel: 'organized-document.pdf',
  },
  {
    id: 'wordToPdf',
    title: 'Word to PDF',
    description: 'Convert DOC/DOCX/RTF/TXT documents to PDF (basic client-side support for TXT/RTF).',
    icon: '📃',
    mode: 'pdf',
    acceptsMultiple: false,
    outputLabel: 'word-to-pdf.pdf',
  },
  {
    id: 'split',
    title: 'Split PDF',
    description: 'Split every page of a PDF into separate files packed in a ZIP.',
    icon: '✂️',
    mode: 'pdf',
    acceptsMultiple: false,
    outputLabel: 'split-pages.zip',
  },
  {
    id: 'compress',
    title: 'Compress PDF',
    description: 'Optimize a PDF locally using object streams and clean saving.',
    icon: '🗜️',
    mode: 'pdf',
    acceptsMultiple: false,
    outputLabel: 'compressed-document.pdf',
  },
  {
    id: 'rotate',
    title: 'Rotate PDF',
    description: 'Rotate all pages or selected pages by 90, 180, or 270 degrees.',
    icon: '🔄',
    mode: 'pdf',
    acceptsMultiple: false,
    outputLabel: 'rotated-document.pdf',
  },
  {
    id: 'delete',
    title: 'Delete Pages',
    description: 'Remove selected pages and export a clean PDF.',
    icon: '🗑️',
    mode: 'pdf',
    acceptsMultiple: false,
    outputLabel: 'pages-deleted.pdf',
  },
  {
    id: 'extract',
    title: 'Extract Pages',
    description: 'Extract selected pages into a new PDF file.',
    icon: '📄',
    mode: 'pdf',
    acceptsMultiple: false,
    outputLabel: 'extracted-pages.pdf',
  },
  {
    id: 'reorder',
    title: 'Reorder Pages',
    description: 'Create a new PDF using a custom page order.',
    icon: '↕️',
    mode: 'pdf',
    acceptsMultiple: false,
    outputLabel: 'reordered-document.pdf',
  },
  {
    id: 'imageToPdf',
    title: 'Image to PDF',
    description: 'Convert JPG and PNG files into a single multi-page PDF.',
    icon: '🖼️',
    mode: 'image',
    acceptsMultiple: true,
    outputLabel: 'images-document.pdf',
  },
  {
    id: 'pdfToImage',
    title: 'PDF to Image',
    description: 'Render every PDF page as high-quality PNG images in a ZIP.',
    icon: '🌄',
    mode: 'pdf',
    acceptsMultiple: false,
    outputLabel: 'pdf-images.zip',
  },
  {
    id: 'watermark',
    title: 'Add Watermark',
    description: 'Draw text watermark overlays on all pages of a PDF document.',
    icon: '🏷️',
    mode: 'pdf',
    acceptsMultiple: false,
    outputLabel: 'watermarked-document.pdf',
  },
  {
    id: 'pagenumber',
    title: 'Add Page Numbers',
    description: 'Stamp sequential page numbering at the bottom of each page.',
    icon: '🔢',
    mode: 'pdf',
    acceptsMultiple: false,
    outputLabel: 'paginated-document.pdf',
  },
  {
    id: 'protect',
    title: 'Protect PDF',
    description: 'Encrypt a PDF file with a password to restrict viewing.',
    icon: '🔒',
    mode: 'pdf',
    acceptsMultiple: false,
    outputLabel: 'protected-document.pdf',
  },
  {
    id: 'unlock',
    title: 'Unlock PDF',
    description: 'Decrypt password security from a PDF to save a free version.',
    icon: '🔓',
    mode: 'pdf',
    acceptsMultiple: false,
    outputLabel: 'unlocked-document.pdf',
  },
  {
    id: 'extractImages',
    title: 'Extract Images',
    description: 'Pull all embedded image assets out of a PDF into a ZIP folder.',
    icon: '🖼️',
    mode: 'pdf',
    acceptsMultiple: false,
    outputLabel: 'extracted-images.zip',
  },
  {
    id: 'extractText',
    title: 'Extract Text',
    description: 'Perform text scraping from all PDF pages into a plain text output.',
    icon: '📝',
    mode: 'pdf',
    acceptsMultiple: false,
    outputLabel: 'extracted-text.txt',
  },
  {
    id: 'excelToPdf',
    title: 'Excel to PDF',
    description: 'Convert XLS/XLSX workbooks to structured PDF tables.',
    icon: '📊',
    mode: 'excel',
    acceptsMultiple: false,
    outputLabel: 'excel-converted.pdf',
  },
  {
    id: 'pdfToExcel',
    title: 'PDF to Excel',
    description: 'Extract tables and textual layouts from a PDF to an XLSX workbook.',
    icon: '📈',
    mode: 'pdf',
    acceptsMultiple: false,
    outputLabel: 'pdf-converted.xlsx',
  },
]
