import { Puzzle, Scissors, Minimize2, Compass, RefreshCw, Trash2, FileText, ArrowUpDown, Image, Wand2, ClipboardList, BarChart2, Grid, BookOpen, Folders, FileEdit, Mail, Bot, PenTool, Building, TrendingDown, TrendingUp, Shuffle, Upload, Save, Lightbulb, Landmark, Hospital, ScrollText, Calendar, Search, Binary, MessageSquare, Tag, Folder, Monitor, Key, Hash, Radio, Ruler, User, Sparkles, BadgeCheck, Pen, MessageCircle, FlaskConical } from 'lucide-react'
export interface ToolRegistryEntry {
  id: string
  title: string
  description: string
  category: 'PDF' | 'Excel' | 'Word' | 'PPT' | 'Image' | 'AI' | 'Govt' | 'Developer' | 'Stats'
  icon: React.ReactNode
  route: string
  keywords: string[]
  badge?: string
}

export const toolRegistry: ToolRegistryEntry[] = [
  /* PDF Suite */
  {
    id: 'pdf-merge',
    title: 'Merge PDF',
    description: 'Combine multiple PDF files into one organized document.',
    category: 'PDF',
    icon: <Puzzle size={24} />,
    route: '/pdf/merge',
    keywords: ['merge', 'combine', 'join', 'pdf', 'concat'],
  },
  {
    id: 'pdf-split',
    title: 'Split PDF',
    description: 'Split every page of a PDF into separate files packed in a ZIP.',
    category: 'PDF',
    icon: <Scissors size={24} />,
    route: '/pdf/split',
    keywords: ['split', 'cut', 'divide', 'separate', 'pdf', 'zip'],
  },
  {
    id: 'pdf-compress',
    title: 'Compress PDF',
    description: 'Optimize and reduce PDF file size using local compression presets.',
    category: 'PDF',
    icon: <Minimize2 size={24} />,
    route: '/pdf/compress',
    keywords: ['compress', 'shrink', 'size', 'pdf', 'minify'],
  },
  {
    id: 'pdf-organize',
    title: 'Organize PDF',
    description: 'Visually reorder, rotate, delete, or manage pages in a PDF document.',
    category: 'PDF',
    icon: <Compass size={24} />,
    route: '/pdf/organize',
    keywords: ['organize', 'rearrange', 'reorder', 'rotate', 'delete', 'pdf'],
  },
  {
    id: 'pdf-rotate',
    title: 'Rotate PDF',
    description: 'Rotate selected pages by 90, 180, or 270 degrees.',
    category: 'PDF',
    icon: <RefreshCw size={24} />,
    route: '/pdf/rotate',
    keywords: ['rotate', 'turn', 'orientation', 'landscape', 'portrait', 'pdf'],
  },
  {
    id: 'pdf-delete',
    title: 'Delete Pages',
    description: 'Remove selected pages and export a clean PDF document.',
    category: 'PDF',
    icon: <Trash2 size={24} />,
    route: '/pdf/delete',
    keywords: ['delete', 'remove', 'strip', 'clean', 'pdf'],
  },
  {
    id: 'pdf-extract',
    title: 'Extract Pages',
    description: 'Extract specific pages into a new standalone PDF.',
    category: 'PDF',
    icon: <FileText size={24} />,
    route: '/pdf/extract',
    keywords: ['extract', 'select', 'get', 'pages', 'pdf'],
  },
  {
    id: 'pdf-reorder',
    title: 'Reorder Pages',
    description: 'Create a new PDF using a custom, ordered list of pages.',
    category: 'PDF',
    icon: <ArrowUpDown size={24} />,
    route: '/pdf/reorder',
    keywords: ['reorder', 'sort', 'arrange', 'pdf'],
  },
  {
    id: 'pdf-image-to-pdf',
    title: 'Image to PDF',
    description: 'Convert JPG and PNG files into a single multi-page PDF.',
    category: 'PDF',
    icon: <Image size={24} />,
    route: '/pdf/image-to-pdf',
    keywords: ['image', 'jpg', 'png', 'convert', 'pdf'],
  },
  {
    id: 'pdf-pdf-to-image',
    title: 'PDF to Image',
    description: 'Render every PDF page as high-quality PNG images inside a ZIP.',
    category: 'PDF',
    icon: <Image size={24} />,
    route: '/pdf/pdf-to-image',
    keywords: ['pdf', 'png', 'jpg', 'render', 'extract', 'zip'],
  },
  {
    id: 'pdf-word-to-pdf',
    title: 'Word to PDF',
    description: 'Convert DOC/DOCX/RTF/TXT files to PDF.',
    category: 'PDF',
    icon: <FileText size={24} />,
    route: '/pdf/word-to-pdf',
    keywords: ['word', 'docx', 'doc', 'txt', 'rtf', 'convert', 'pdf'],
  },

  /* Excel Suite */
  {
    id: 'excel-merge',
    title: 'Merge Spreadsheets',
    description: 'Combine rows from multiple CSV or XLSX sheets into one consolidated sheet.',
    category: 'Excel',
    icon: <Puzzle size={24} />,
    route: '/excel/merge',
    keywords: ['merge', 'excel', 'csv', 'xlsx', 'combine', 'sheets'],
  },
  {
    id: 'excel-remove-duplicates',
    title: 'Remove Duplicates',
    description: 'Detect and delete identical rows using custom unique keys.',
    category: 'Excel',
    icon: <Wand2 size={24} />,
    route: '/excel/remove-duplicates',
    keywords: ['duplicates', 'clean', 'excel', 'csv', 'xlsx', 'dedup', 'rows'],
  },
  {
    id: 'excel-csv-to-xlsx',
    title: 'CSV → XLSX',
    description: 'Convert plain text CSV files into formatted Excel sheets.',
    category: 'Excel',
    icon: <RefreshCw size={24} />,
    route: '/excel/csv-to-xlsx',
    keywords: ['csv', 'xlsx', 'excel', 'convert', 'format'],
  },
  {
    id: 'excel-xlsx-to-csv',
    title: 'XLSX → CSV',
    description: 'Export Excel sheet tabs as UTF-8 comma-separated files.',
    category: 'Excel',
    icon: <ClipboardList size={24} />,
    route: '/excel/xlsx-to-csv',
    keywords: ['xlsx', 'csv', 'excel', 'export', 'convert'],
  },
  {
    id: 'excel-frequency',
    title: 'Frequency Tables',
    description: 'Generate percentage distributions and occurrence tables for columns.',
    category: 'Excel',
    icon: <BarChart2 size={24} />,
    route: '/excel/frequency',
    keywords: ['frequency', 'distribution', 'statistics', 'count', 'excel', 'csv'],
  },
  {
    id: 'excel-crosstab',
    title: 'Crosstab Generator',
    description: 'Build contingency/cross-tabulation matrices for data analysis.',
    category: 'Excel',
    icon: <Grid size={24} />,
    route: '/excel/crosstab',
    keywords: ['crosstab', 'contingency', 'pivot', 'matrix', 'cross-tab', 'excel'],
  },

  /* Word Suite */
  {
    id: 'word-to-pdf-suite',
    title: 'Word to PDF Converter',
    description: 'Process word documents into clean PDF outputs in your browser.',
    category: 'Word',
    icon: <FileText size={24} />,
    route: '/word/to-pdf',
    keywords: ['word', 'docx', 'doc', 'convert', 'pdf'],
  },
  {
    id: 'word-pdf-to-word',
    title: 'PDF to Word Converter',
    description: 'Extract layout and text from PDF documents into editable Word outputs.',
    category: 'Word',
    icon: <BookOpen size={24} />,
    route: '/word/pdf-to-word',
    keywords: ['pdf', 'word', 'docx', 'extract', 'convert'],
  },
  {
    id: 'word-docx-merge',
    title: 'DOCX Merge',
    description: 'Combine multiple Word documents into a single unified DOCX.',
    category: 'Word',
    icon: <Folders size={24} />,
    route: '/word/docx-merge',
    keywords: ['merge', 'docx', 'doc', 'combine', 'word'],
  },
  {
    id: 'word-template-fill',
    title: 'Template Filler',
    description: 'Parse text templates and fill them out with structured keys.',
    category: 'Word',
    icon: <FileEdit size={24} />,
    route: '/word/template-fill',
    keywords: ['template', 'fill', 'form', 'replace', 'variables'],
  },
  {
    id: 'word-mail-merge',
    title: 'Mail Merge',
    description: 'Generate bulk filled templates from a base file and list of values.',
    category: 'Word',
    icon: <Mail size={24} />,
    route: '/word/mail-merge',
    keywords: ['mail', 'merge', 'bulk', 'letters', 'documents', 'excel'],
  },
  {
    id: 'word-ai-report',
    title: 'AI Report Writer',
    description: 'Structure and generate formal business reports with local AI prompts.',
    category: 'Word',
    icon: <Bot size={24} />,
    route: '/word/ai-report',
    keywords: ['ai', 'report', 'generator', 'write', 'draft'],
  },
  {
    id: 'word-ai-letter',
    title: 'AI Letter Writer',
    description: 'Draft official letters, cover notes, or applications using AI templates.',
    category: 'Word',
    icon: <PenTool size={24} />,
    route: '/word/ai-letter',
    keywords: ['ai', 'letter', 'write', 'draft', 'application'],
  },
  {
    id: 'word-ai-office-note',
    title: 'AI Office Note Generator',
    description: 'Generate standard double-spaced office notes and circulars using AI.',
    category: 'Word',
    icon: <Building size={24} />,
    route: '/word/ai-office-note',
    keywords: ['ai', 'office', 'note', 'green note', 'file note'],
  },

  /* PowerPoint Suite */
  {
    id: 'ppt-to-pdf',
    title: 'PPT to PDF',
    description: 'Convert PowerPoint files to PDF pages client-side.',
    category: 'PPT',
    icon: <TrendingDown size={24} />,
    route: '/ppt/ppt-to-pdf',
    keywords: ['ppt', 'pptx', 'pdf', 'convert', 'slides'],
  },
  {
    id: 'pdf-to-ppt',
    title: 'PDF to PPT',
    description: 'Convert PDF files back into PowerPoint slide decks.',
    category: 'PPT',
    icon: <TrendingUp size={24} />,
    route: '/ppt/pdf-to-ppt',
    keywords: ['pdf', 'ppt', 'pptx', 'convert', 'slides'],
  },
  {
    id: 'ppt-slide-reorder',
    title: 'Slide Reorder',
    description: 'Reorder presentation slides visually before exporting.',
    category: 'PPT',
    icon: <Shuffle size={24} />,
    route: '/ppt/slide-reorder',
    keywords: ['reorder', 'move', 'slides', 'ppt', 'pptx'],
  },
  {
    id: 'ppt-slide-extract',
    title: 'Slide Extractor',
    description: 'Extract specific presentation slides into a separate PPT deck.',
    category: 'PPT',
    icon: <Upload size={24} />,
    route: '/ppt/slide-extract',
    keywords: ['extract', 'select', 'slides', 'ppt', 'pptx'],
  },
  {
    id: 'ppt-slide-export',
    title: 'Slide Exporter',
    description: 'Save presentation slides as individual PNG images or SVGs.',
    category: 'PPT',
    icon: <Save size={24} />,
    route: '/ppt/slide-export',
    keywords: ['export', 'save', 'png', 'slides', 'ppt', 'pptx'],
  },
  {
    id: 'ppt-topic-to-ppt',
    title: 'Topic to Presentation',
    description: 'Provide a topic and let AI draft a slide presentation outline and deck.',
    category: 'PPT',
    icon: <Lightbulb size={24} />,
    route: '/ppt/topic-to-ppt',
    keywords: ['ai', 'presentation', 'topic', 'slides', 'ppt', 'pptx', 'generator'],
  },
  {
    id: 'ppt-report-to-ppt',
    title: 'Report to PPT',
    description: 'Summarize a text report into a presentation slide deck.',
    category: 'PPT',
    icon: <BarChart2 size={24} />,
    route: '/ppt/report-to-ppt',
    keywords: ['ai', 'report', 'slides', 'ppt', 'pptx', 'convert', 'summarize'],
  },
  {
    id: 'ppt-gov-presentation',
    title: 'Government PPT Generator',
    description: 'Create standard government review meetings or department summary slide decks.',
    category: 'PPT',
    icon: <Landmark size={24} />,
    route: '/ppt/gov-presentation',
    keywords: ['ai', 'government', 'meeting', 'slides', 'ppt', 'pptx', 'review'],
  },

  /* Image Suite */
  {
    id: 'image-compress',
    title: 'Image Compressor',
    description: 'Reduce JPG, PNG, and WebP dimensions and weight instantly.',
    category: 'Image',
    icon: <Minimize2 size={24} />,
    route: '/image/compress',
    keywords: ['compress', 'image', 'png', 'jpg', 'shrink', 'quality'],
  },
  {
    id: 'image-resize',
    title: 'Resize & Crop Image',
    description: 'Resize image dimensions or crop custom selection boundaries.',
    category: 'Image',
    icon: <Ruler size={24} />,
    route: '/image/resize',
    keywords: ['resize', 'crop', 'width', 'height', 'dimensions', 'image'],
  },
  {
    id: 'image-convert',
    title: 'Convert Image Format',
    description: 'Transform images between JPG, PNG, WebP, SVG, and PDF.',
    category: 'Image',
    icon: <RefreshCw size={24} />,
    route: '/image/convert',
    keywords: ['convert', 'image', 'format', 'png', 'jpg', 'webp', 'svg'],
  },
  {
    id: 'image-remove-bg',
    title: 'Background Remover',
    description: 'Isolate subjects and erase backgrounds using canvas operations.',
    category: 'Image',
    icon: <User size={24} />,
    route: '/image/remove-bg',
    keywords: ['background', 'remover', 'subject', 'transparent', 'cutout'],
  },
  {
    id: 'image-upscale',
    title: 'AI Upscaler & Enhancer',
    description: 'Upscale resolution and clean noise/contrast locally.',
    category: 'Image',
    icon: <Sparkles size={24} />,
    route: '/image/upscale',
    keywords: ['upscale', 'enhance', 'resolution', 'denoise', 'super-res'],
  },
  {
    id: 'image-passport',
    title: 'Passport Photo Maker',
    description: 'Auto-align and crop photo to formal passport sizes with standard backdrops.',
    category: 'Image',
    icon: <BadgeCheck size={24} />,
    route: '/image/passport-photo',
    keywords: ['passport', 'photo', 'crop', 'visa', 'officials', 'stamp'],
  },
  {
    id: 'image-signature',
    title: 'Signature Extractor',
    description: 'Isolate and extract handwritten signatures from scans to transparent PNGs.',
    category: 'Image',
    icon: <Pen size={24} />,
    route: '/image/extract-signature',
    keywords: ['signature', 'extractor', 'transparent', 'extract', 'sign', 'png'],
  },
  {
    id: 'image-scanner',
    title: 'Document Scanner',
    description: 'Binarize scans, clean perspective skew, and increase contrast.',
    category: 'Image',
    icon: <Search size={24} />,
    route: '/image/scanner',
    keywords: ['scan', 'scanner', 'perspective', 'contrast', 'binarize', 'document'],
  },

  /* AI Suite */
  {
    id: 'ai-assistant',
    title: 'AI Document Assistant',
    description: 'Chat with uploaded PDF, Word, Excel, CSV, or Image files.',
    category: 'AI',
    icon: <MessageCircle size={24} />,
    route: '/ai/assistant',
    keywords: ['chat', 'pdf', 'excel', 'word', 'csv', 'assistant', 'prompt', 'ask'],
  },
  {
    id: 'ai-report-gen',
    title: 'AI Report Generator',
    description: 'Draft official office briefs, meeting minutes, and tabular notes.',
    category: 'AI',
    icon: <BarChart2 size={24} />,
    route: '/ai/report-gen',
    keywords: ['report', 'generate', 'minutes', 'office note', 'summarize'],
  },
  {
    id: 'ai-research',
    title: 'AI Research Assistant',
    description: 'Deep-scan multiple research/legal documents to summarize findings.',
    category: 'AI',
    icon: <FlaskConical size={24} />,
    route: '/ai/research',
    keywords: ['research', 'summarize', 'find', 'reference', 'legal', 'academic'],
  },
  {
    id: 'ai-content-gen',
    title: 'AI Content Generator',
    description: 'Draft press releases, social posts, and official announcements.',
    category: 'AI',
    icon: <PenTool size={24} />,
    route: '/ai/content-gen',
    keywords: ['content', 'write', 'press release', 'social media', 'drafting'],
  },

  /* Government Suite */
  {
    id: 'govt-hlb',
    title: 'HLB Consolidator',
    description: 'Consolidate multiple CHC/PHC local health block reports into a single sheet.',
    category: 'Govt',
    icon: <Hospital size={24} />,
    route: '/govt/hlb',
    keywords: ['hlb', 'consolidate', 'health', 'block', 'aggregate', 'report'],
  },
  {
    id: 'govt-office-note',
    title: 'Office Note Generator',
    description: 'Create standardized government office notes with green margins and reference headers.',
    category: 'Govt',
    icon: <Building size={24} />,
    route: '/govt/office-note',
    keywords: ['office note', 'green note', 'note sheet', 'file drafting', 'govt'],
  },
  {
    id: 'govt-do-letter',
    title: 'D.O. Letter Generator',
    description: 'Draft Demi-Official (D.O.) letters with formal state emblem and header slots.',
    category: 'Govt',
    icon: <Mail size={24} />,
    route: '/govt/do-letter',
    keywords: ['do letter', 'demi-official', 'letterhead', 'formal letter', 'govt'],
  },
  {
    id: 'govt-rti-draft',
    title: 'RTI Draft Generator',
    description: 'Draft formal Right To Information (RTI) query templates with auto-legal text.',
    category: 'Govt',
    icon: <ScrollText size={24} />,
    route: '/govt/rti-draft',
    keywords: ['rti', 'right to information', 'appeal', 'application', 'govt'],
  },
  {
    id: 'govt-minutes',
    title: 'Meeting Minutes Generator',
    description: 'Generate standard government meeting minutes listing members, decisions, and action items.',
    category: 'Govt',
    icon: <Calendar size={24} />,
    route: '/govt/minutes',
    keywords: ['minutes', 'mom', 'meeting', 'action items', 'govt'],
  },
  {
    id: 'govt-inspection',
    title: 'Inspection Report Generator',
    description: 'Build field inspection notes, compliance reports, and site visit logs.',
    category: 'Govt',
    icon: <Search size={24} />,
    route: '/govt/inspection',
    keywords: ['inspection', 'audit', 'site visit', 'report', 'govt'],
  },
  {
    id: 'govt-stats-builder',
    title: 'Statistical Report Builder',
    description: 'Compile public sector statistics into standardized tables for official releases.',
    category: 'Govt',
    icon: <BarChart2 size={24} />,
    route: '/govt/stats-builder',
    keywords: ['statistics', 'builder', 'tables', 'tabulation', 'census', 'govt'],
  },
  {
    id: 'govt-census-format',
    title: 'Census Data Formatter',
    description: 'Format district demographic tables and population CSV/XLSX logs.',
    category: 'Govt',
    icon: <Binary size={24} />,
    route: '/govt/census-format',
    keywords: ['census', 'demography', 'district', 'clean data', 'govt'],
  },
  {
    id: 'govt-translation',
    title: 'Official Translation Tool',
    description: 'Translate government letters between state and national languages locally.',
    category: 'Govt',
    icon: <MessageSquare size={24} />,
    route: '/govt/translation',
    keywords: ['translation', 'hindi', 'english', 'state language', 'translate'],
  },
  {
    id: 'govt-naming-standard',
    title: 'File Naming Standardizer',
    description: 'Standardize digital files according to official department catalog rules.',
    category: 'Govt',
    icon: <Tag size={24} />,
    route: '/govt/naming-standard',
    keywords: ['naming', 'standard', 'file naming', 'archival', 'nomenclature'],
  },

  /* Developer Suite */
  {
    id: 'dev-json',
    title: 'JSON Formatter & Validator',
    description: 'Format nested JSON outputs, minify keys, and highlight syntactic errors.',
    category: 'Developer',
    icon: <Folder size={24} />,
    route: '/developer/json',
    keywords: ['json', 'format', 'minify', 'validate', 'lint', 'prettify'],
  },
  {
    id: 'dev-csv-json',
    title: 'CSV ⇆ JSON Converter',
    description: 'Convert grid data between CSV table structures and JSON objects.',
    category: 'Developer',
    icon: <RefreshCw size={24} />,
    route: '/developer/csv-json',
    keywords: ['csv', 'json', 'convert', 'parse', 'stringify'],
  },
  {
    id: 'dev-xml',
    title: 'XML Formatter',
    description: 'Format and prettify XML documents, with node tree indentation.',
    category: 'Developer',
    icon: <Monitor size={24} />,
    route: '/developer/xml',
    keywords: ['xml', 'prettify', 'format', 'tag', 'html'],
  },
  {
    id: 'dev-base64',
    title: 'Base64 Encoder/Decoder',
    description: 'Encode string files or decode binary hashes into data URIs locally.',
    category: 'Developer',
    icon: <Key size={24} />,
    route: '/developer/base64',
    keywords: ['base64', 'encode', 'decode', 'binary', 'string', 'crypt'],
  },
  {
    id: 'dev-hash',
    title: 'Hash Generator',
    description: 'Generate MD5, SHA-1, and SHA-256 integrity checksums for text inputs.',
    category: 'Developer',
    icon: <Hash size={24} />,
    route: '/developer/hash',
    keywords: ['hash', 'md5', 'sha1', 'sha256', 'checksum', 'crypto'],
  },
  {
    id: 'dev-api-tester',
    title: 'REST API Tester',
    description: 'Test API endpoints locally, send custom HTTP methods, headers, and request body.',
    category: 'Developer',
    icon: <Radio size={24} />,
    route: '/developer/api-tester',
    keywords: ['api', 'rest', 'http', 'fetch', 'postman', 'curl', 'request'],
  },
]
